DATA PREPROCESSING (ASSIGNMENT -1)

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

# IMPORTING DATASET

In [14]:
dataset=pd.read_csv('C:/Users/gkeer/Downloads/salary')
dataset

Date        Open        High         Low       Close   Adj_Close  \
0     2000/3/27    3.812500    4.156250    3.812500    4.125000    4.125000   
1     2000/3/28    4.125000    4.125000    4.000000    4.015625    4.015625   
2     2000/3/29    4.000000    4.031250    3.953125    4.000000    4.000000   
3     2000/3/30    4.000000    4.000000    3.843750    3.843750    3.843750   
4     2000/3/31    3.734375    3.734375    3.390625    3.390625    3.390625   
...         ...         ...         ...         ...         ...         ...   
4387   2017/9/1  113.790001  114.099998  112.790001  113.309998  113.309998   
4388   2017/9/5  112.519997  113.529999  111.160004  111.870003  111.870003   
4389   2017/9/6  112.029999  112.489998  110.250000  112.230003  112.230003   
4390   2017/9/7  112.459999  112.900002  112.000000  112.339996  112.339996   
4391   2017/9/8  112.300003  114.790001  112.010002  113.190002  113.190002   

       Volume  
0     3675600  
1     1077600  
2      437200  
3     1883600  
4     7931600  
...       ...  
4387   950000  
4388  1805200  
4389  2136700  
4390  1251600  
4391  1611700  

[4392 rows x 7 columns]

In [15]:
import random
ix = [(row, col) for row in range(dataset.shape[0]) for col in range(dataset.shape[1])]
for row, col in random.sample(ix, int(round(.1*len(ix)))):
    dataset.iat[row, col] = np.nan

In [16]:
dataset

Date        Open        High         Low       Close   Adj_Close  \
0     2000/3/27    3.812500    4.156250    3.812500         NaN         NaN   
1     2000/3/28    4.125000    4.125000    4.000000    4.015625    4.015625   
2           NaN    4.000000    4.031250    3.953125         NaN    4.000000   
3     2000/3/30    4.000000         NaN    3.843750    3.843750    3.843750   
4           NaN         NaN    3.734375    3.390625         NaN    3.390625   
...         ...         ...         ...         ...         ...         ...   
4387   2017/9/1  113.790001  114.099998  112.790001         NaN  113.309998   
4388   2017/9/5  112.519997  113.529999  111.160004  111.870003  111.870003   
4389        NaN  112.029999  112.489998  110.250000  112.230003  112.230003   
4390   2017/9/7  112.459999         NaN  112.000000  112.339996  112.339996   
4391   2017/9/8  112.300003  114.790001  112.010002  113.190002  113.190002   

         Volume  
0           NaN  
1     1077600.0  
2      437200.0  
3     1883600.0  
4     7931600.0  
...         ...  
4387        NaN  
4388        NaN  
4389  2136700.0  
4390  1251600.0  
4391  1611700.0  

[4392 rows x 7 columns]

In [17]:
dataset=dataset.drop(['Date','Adj_Close'],axis=1)
dataset

Open        High         Low       Close     Volume
0       3.812500    4.156250    3.812500         NaN        NaN
1       4.125000    4.125000    4.000000    4.015625  1077600.0
2       4.000000    4.031250    3.953125         NaN   437200.0
3       4.000000         NaN    3.843750    3.843750  1883600.0
4            NaN    3.734375    3.390625         NaN  7931600.0
...          ...         ...         ...         ...        ...
4387  113.790001  114.099998  112.790001         NaN        NaN
4388  112.519997  113.529999  111.160004  111.870003        NaN
4389  112.029999  112.489998  110.250000  112.230003  2136700.0
4390  112.459999         NaN  112.000000  112.339996  1251600.0
4391  112.300003  114.790001  112.010002  113.190002  1611700.0

[4392 rows x 5 columns]

In [18]:
dataset.describe()

Open         High          Low        Close        Volume
count  3944.000000  3966.000000  3953.000000  3982.000000  3.938000e+03
mean     30.365155    31.016600    30.082124    30.478526  1.884715e+06
std      29.787025    30.406837    29.593366    29.844361  1.615297e+06
min       3.296875     3.562500     3.000000     3.250000  1.904000e+05
25%       8.685625     8.788750     8.575000     8.644375  1.084600e+06
50%      14.688750    14.995000    14.435000    14.737500  1.540600e+06
75%      42.436250    43.128751    41.945000    42.518750  2.188550e+06
max     121.080002   121.750000   120.169998   121.360001  4.641260e+07

In [19]:
print(dataset.isnull().sum())

Open      448
High      426
Low       439
Close     410
Volume    454
dtype: int64


In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4392 entries, 0 to 4391
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    3944 non-null   float64
 1   High    3966 non-null   float64
 2   Low     3953 non-null   float64
 3   Close   3982 non-null   float64
 4   Volume  3938 non-null   float64
dtypes: float64(5)
memory usage: 171.7 KB


# SPLIT INTO INDEPENDENT AND DEPENDENT VALUES

In [21]:
x=dataset.iloc[:,:-1].values
x

array([[  3.8125  ,   4.15625 ,   3.8125  ,        nan],
       [  4.125   ,   4.125   ,   4.      ,   4.015625],
       [  4.      ,   4.03125 ,   3.953125,        nan],
       ...,
       [112.029999, 112.489998, 110.25    , 112.230003],
       [112.459999,        nan, 112.      , 112.339996],
       [112.300003, 114.790001, 112.010002, 113.190002]])

In [22]:
y=dataset[['Volume']].values
y

array([[     nan],
       [1077600.],
       [ 437200.],
       ...,
       [2136700.],
       [1251600.],
       [1611700.]])

In [23]:
x[:,0:1]

array([[  3.8125  ],
       [  4.125   ],
       [  4.      ],
       ...,
       [112.029999],
       [112.459999],
       [112.300003]])

In [24]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,0:4])
x[:,0:4]=imputer.transform(x[:,0:4])
x

array([[  3.8125    ,   4.15625   ,   3.8125    ,  30.47852621],
       [  4.125     ,   4.125     ,   4.        ,   4.015625  ],
       [  4.        ,   4.03125   ,   3.953125  ,  30.47852621],
       ...,
       [112.029999  , 112.489998  , 110.25      , 112.230003  ],
       [112.459999  ,  31.01659994, 112.        , 112.339996  ],
       [112.300003  , 114.790001  , 112.010002  , 113.190002  ]])

# SPLITTING DATASET INTO TRAINING AND TESTING

In [25]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [26]:
print(x_train)

[[11.875      11.9675     11.8225     11.83      ]
 [11.1175     11.1225     11.0075     11.07      ]
 [49.439999   49.75       30.08212398 49.59      ]
 ...
 [ 7.2625      7.2775      7.24        7.27      ]
 [78.790001   79.779999   78.339996   78.839996  ]
 [ 5.3075      5.325       5.         30.47852621]]


In [27]:
print(x_test)

[[74.894997   75.205002   30.08212398 73.385002  ]
 [42.110001   42.360001   41.555      41.685001  ]
 [ 6.775       6.775       6.6975      6.7025    ]
 ...
 [12.3675     12.3825     12.265      12.375     ]
 [ 7.1625      7.39        6.85        6.85      ]
 [43.52       43.855      43.189999   43.709999  ]]


In [28]:
print(y_train)

[[     nan]
 [ 994400.]
 [ 893400.]
 ...
 [1412000.]
 [2080300.]
 [ 742800.]]


In [29]:
print(y_test)

[[3527800.]
 [1367600.]
 [ 760000.]
 ...
 [     nan]
 [1508000.]
 [2038000.]]


# FEATURE SCALING

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[-0.64810942 -0.65393345 -0.64369855 -0.64735721]
 [-0.6750304  -0.68327755 -0.67283658 -0.6740822 ]
 [ 0.68692274  0.65812967  0.00912284  0.6804528 ]
 ...
 [-0.81203424 -0.81680187 -0.80753292 -0.80770715]
 [ 1.73        1.70097369  1.73444705  1.70901312]
 [-0.88151349 -0.88460583 -0.88761781  0.00840814]]
[[ 1.5376422   1.49274964 -0.02699186  1.48925612]
 [ 0.38586918  0.36650774  0.37754318  0.37026173]
 [-0.85548832 -0.85368766 -0.85153661 -0.8646033 ]
 ...
 [-0.65901764 -0.66140874 -0.65522587 -0.66436685]
 [-0.84187502 -0.83259956 -0.84615944 -0.85939662]
 [ 0.435404    0.41777066  0.43519345  0.44174316]]
